package com.wallet.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.wallet.dto.DepositRequest;
import com.wallet.dto.TradeRequest;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.UUID;

import static org.hamcrest.Matchers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc
@Transactional
@DisplayName("WalletController API Tests")
public class WalletControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    private static String uuid() {
        // Random UUID (version 4) generated by java.util.UUID.
        UUID uuid = UUID.randomUUID();
        return uuid.toString();
    }

    @Test
    @DisplayName("POST /wallets/{userId}/deposit should return 200 and success")
    void testDepositEndpoint() throws Exception {
        // Arrange
        String userId = uuid();
        DepositRequest request = new DepositRequest(new BigDecimal("100.00"), uuid(), userId);

        // Act & Assert
        mockMvc.perform(post("/wallets/{userId}/deposit", userId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.status", is("success")))
            .andExpect(jsonPath("$.newBalance", is(100.0)));
    }

    @Test
    @DisplayName("POST /wallets/{userId}/trade should return 200 for valid trade")
    void testTradeEndpointWithSufficientBalance() throws Exception {
        // Arrange
        String userId = uuid();
        
        // First deposit
        mockMvc.perform(post("/wallets/{userId}/deposit", userId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(
                    new DepositRequest(new BigDecimal("500.00"), uuid(), userId))));

        // Then trade
        TradeRequest tradeRequest = new TradeRequest(new BigDecimal("200.00"), uuid());

        // Act & Assert
        mockMvc.perform(post("/wallets/{userId}/trade", userId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(tradeRequest)))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.status", is("success")))
            .andExpect(jsonPath("$.newBalance", is(300.0)));
    }

    @Test
    @DisplayName("POST /wallets/{userId}/trade should return 400 for insufficient balance")
    void testTradeEndpointWithInsufficientBalance() throws Exception {
        // Arrange
        String userId = uuid();
        
        // Deposit small amount
        mockMvc.perform(post("/wallets/{userId}/deposit", userId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(
                    new DepositRequest(new BigDecimal("50.00"), uuid(), userId))));

        // Try to trade more than balance
        TradeRequest tradeRequest = new TradeRequest(new BigDecimal("100.00"), uuid());

        // Act & Assert
        mockMvc.perform(post("/wallets/{userId}/trade", userId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(tradeRequest)))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.status", is("error")))
            .andExpect(jsonPath("$.message", containsString("Insufficient balance")));
    }

    @Test
    @DisplayName("GET /wallets/{userId} should return wallet balance and history")
    void testGetWalletEndpoint() throws Exception {
        // Arrange
        String userId = uuid();
        
        // Deposit
        mockMvc.perform(post("/wallets/{userId}/deposit", userId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(
                    new DepositRequest(new BigDecimal("200.00"), uuid(), userId))));

        // Trade
        mockMvc.perform(post("/wallets/{userId}/trade", userId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(
                    new TradeRequest(new BigDecimal("50.00"), uuid()))));

        // Act & Assert
        mockMvc.perform(get("/wallets/{userId}", userId))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.walletId").isNotEmpty())
            .andExpect(jsonPath("$.userId", is(userId)))
            .andExpect(jsonPath("$.balance", is(150.0)))
            .andExpect(jsonPath("$.transactions", hasSize(2)))
            .andExpect(jsonPath("$.transactions[0].type", is("TRADE")))
            .andExpect(jsonPath("$.transactions[1].type", is("DEPOSIT")));
    }

    @Test
    @DisplayName("GET /wallets/{userId} for non-existent user should return zero balance")
    void testGetWalletForNonExistentUser() throws Exception {
        // Act & Assert
        String userId = uuid();

        mockMvc.perform(get("/wallets/{userId}", userId))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.userId", is(userId)))
            .andExpect(jsonPath("$.balance").isNumber())
            .andExpect(jsonPath("$.transactions", hasSize(0)));
    }

    @Test
    @DisplayName("Idempotency: Retried deposit should not duplicate")
    void testDepositIdempotencyViaAPI() throws Exception {
        // Arrange
        String userId = uuid();
        String idempotencyKey = uuid();
        DepositRequest request = new DepositRequest(new BigDecimal("100.00"), idempotencyKey, idempotencyKey);

        // Act - First request
        mockMvc.perform(post("/wallets/{userId}/deposit", userId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.newBalance", is(100.0)));

        // Act - Retry with same idempotency key
        mockMvc.perform(post("/wallets/{userId}/deposit", userId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.newBalance", is(100.0))); // Should still be 100, not 200

        // Assert - Check final state
        mockMvc.perform(get("/wallets/{userId}", userId))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.balance", is(100.0)))
            .andExpect(jsonPath("$.transactions", hasSize(1))); // Only one transaction
    }

    @Test
    @DisplayName("Idempotency: Retried trade should not duplicate")
    void testTradeIdempotencyViaAPI() throws Exception {
        // Arrange
        String userId = uuid();
        
        // Deposit first
        mockMvc.perform(post("/wallets/{userId}/deposit", userId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(
                    new DepositRequest(new BigDecimal("500.00"), uuid(), userId))));

        String tradeKey = uuid();
        TradeRequest tradeRequest = new TradeRequest(new BigDecimal("100.00"), tradeKey);

        // Act - First trade
        mockMvc.perform(post("/wallets/{userId}/trade", userId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(tradeRequest)))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.newBalance", is(400.0)));

        // Act - Retry trade with same key
        mockMvc.perform(post("/wallets/{userId}/trade", userId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(tradeRequest)))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.newBalance", is(400.0))); // Should still be 400, not 300

        // Assert - Check final state
        mockMvc.perform(get("/wallets/{userId}", userId))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.balance", is(400.0)))
            .andExpect(jsonPath("$.transactions", hasSize(2))); // Deposit + 1 trade
    }

    @Test
    @DisplayName("Invalid deposit amount should return error")
    void testInvalidDepositAmount() throws Exception {
        // Arrange
        String userId = uuid();
        DepositRequest request = new DepositRequest(new BigDecimal("-50.00"), uuid(), userId);

        // Act & Assert
        mockMvc.perform(post("/wallets/{userId}/deposit", userId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.error").exists());
    }

    @Test
    @DisplayName("Invalid idempotency key should return validation error")
    void testInvalidIdempotencyKey() throws Exception {
        // Arrange
        String userId = uuid();
        DepositRequest request = new DepositRequest(new BigDecimal("50.00"), "not-a-uuid-v4", userId);

        // Act & Assert
        mockMvc.perform(post("/wallets/{userId}/deposit", userId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.error", is("Validation Failed")))
            .andExpect(jsonPath("$.details", containsString("UUID v4")));
    }
}
