package com.wallet.service;

import com.wallet.dto.DepositRequest;
import com.wallet.dto.TradeRequest;
import com.wallet.entity.Wallet;
import com.wallet.repository.TransactionRepository;
import com.wallet.repository.UserRepository;
import com.wallet.repository.WalletRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@Transactional
@DisplayName("WalletService Integration Tests")
public class WalletServiceIntegrationTest {

    @Autowired
    private WalletService walletService;

    @Autowired
    private WalletRepository walletRepository;

    @Autowired
    private TransactionRepository transactionRepository;

    @Autowired
    private UserRepository userRepository;

    @BeforeEach
    void setUp() {
        transactionRepository.deleteAll();
        walletRepository.deleteAll();
        userRepository.deleteAll();
    }

    private static String uuid() {
        // Random UUID (version 4) generated by java.util.UUID.
        UUID uuid = UUID.randomUUID();
        return uuid.toString();
    }

    @Test
    @DisplayName("Integration: Deposit and retrieve wallet")
    void testDepositAndGetWallet() {
        String userId = uuid();

        // Act
        walletService.deposit(userId, new DepositRequest(new BigDecimal("100.00"), uuid(), null));
        var response = walletService.getWallet(userId);

        // Assert
        assertEquals(userId, response.getUserId());
        assertEquals(new BigDecimal("100.00"), response.getBalance());
        assertEquals(1, response.getTransactions().size());
    }

    @Test
    @DisplayName("Integration: Multiple operations with history")
    void testMultipleOperationsWithHistory() {
        String userId = uuid();

        // Act
        walletService.deposit(userId, new DepositRequest(new BigDecimal("1000.00"), uuid(), null));
        walletService.trade(userId, new TradeRequest(new BigDecimal("250.00"), uuid()));
        walletService.deposit(userId, new DepositRequest(new BigDecimal("500.00"), uuid(), null));
        walletService.trade(userId, new TradeRequest(new BigDecimal("100.00"), uuid()));

        var response = walletService.getWallet(userId);

        // Assert
        assertEquals(new BigDecimal("1150.00"), response.getBalance());
        assertEquals(4, response.getTransactions().size());
    }

    @Test
    @DisplayName("Integration: Idempotency prevents duplicate operations")
    void testIdempotencyPreventsDoubles() {
        String userId = uuid();
        String idempotencyKey = uuid();

        // Act
        var deposit1 = walletService.deposit(userId, new DepositRequest(new BigDecimal("100.00"), idempotencyKey, null));
        var deposit2 = walletService.deposit(userId, new DepositRequest(new BigDecimal("100.00"), idempotencyKey, null));
        var response = walletService.getWallet(userId);

        // Assert
        assertEquals(deposit1.getNewBalance(), deposit2.getNewBalance());
        assertEquals(1, response.getTransactions().size()); // Only one transaction recorded
    }

    @Test
    @DisplayName("Integration: Trade prevents negative balance")
    void testTradePreventingNegativeBalance() {
        String userId = uuid();

        // Act
        walletService.deposit(userId, new DepositRequest(new BigDecimal("100.00"), uuid(), null));
        var tradeResponse = walletService.trade(userId, 
            new TradeRequest(new BigDecimal("200.00"), uuid()));
        var walletResponse = walletService.getWallet(userId);

        // Assert
        assertEquals("error", tradeResponse.getStatus());
        assertEquals(new BigDecimal("100.00"), walletResponse.getBalance());
        assertEquals(1, walletResponse.getTransactions().size()); // Only deposit
    }

    @Test
    @DisplayName("Integration: Wallet starts at zero for new users")
    void testNewWalletStartsAtZero() {
        String userId = uuid();

        // Act
        var response = walletService.getWallet(userId);

        // Assert
        assertEquals(BigDecimal.ZERO, response.getBalance());
        assertTrue(response.getTransactions().isEmpty());
    }

    @Test
    @DisplayName("Integration: Large number of operations")
    void testManyOperations() {
        String userId = uuid();

        // Act
        BigDecimal balance = BigDecimal.ZERO;
        for (int i = 0; i < 100; i++) {
            balance = balance.add(new BigDecimal("10.00"));
            walletService.deposit(userId, new DepositRequest(new BigDecimal("10.00"), uuid(), null));
        }

        for (int i = 0; i < 50; i++) {
            balance = balance.subtract(new BigDecimal("5.00"));
            walletService.trade(userId, new TradeRequest(new BigDecimal("5.00"), uuid()));
        }

        var response = walletService.getWallet(userId);

        // Assert
        assertEquals(balance, response.getBalance());
        assertEquals(10, response.getTransactions().size());
        assertEquals(150, walletService.getTransactions(userId, 0, 150).getTotalElements());
    }
}
